export const SET_LANG = 'SET_LANG'
export const SET_SELECTOR = 'SET_SELECTOR'
export const SET_RANK_LIST = 'SET_RANK_LIST'
export const SET_CUR_RANK = 'SET_CUR_RANK'
export const SET_CUR_SUB_RANK = 'SET_CUR_SUB_RANK'
export const SET_CUR_TAB = 'SET_CUR_TAB'